import Link from "next/link";
import { pathFor } from "../lib/locales";
// Source copy and markup from published about.html / about-en.html
// at original main 5d97cc458910279646ec10a18ffecaca81a6854d. Only CTA paths and JSX syntax adapted.
function ArabicAbout() {
  return (
<main id="main-content" className="dd-about-page" dir="rtl">
<section className="about-hero"><div className="wrap hero-grid"><div><span className="kicker">Our story</span><h1>الأيام المهمة تستحق اهتمامًا حقيقيًا.</h1><p>Dear Day بدأت من فكرة بسيطة: بدل ما تدور على كل تفصيلة لوحدها، نخلي اليوم كله يتخطط في مكان واحد — بشكل هادئ، واضح، ومصمم حوالين الشخص والمناسبة نفسها.</p></div><div className="hero-collage" aria-label="تفاصيل من تجربة Dear Day"><img className="main-photo" src="/approved-pages/assets/media/complete-package.jpg" alt="تنسيق متكامل لمناسبة من Dear Day"/><img className="small-photo" src="/approved-pages/assets/home/gift-flowers.png" alt="باقة ورد مختارة بعناية"/><div className="brand-note"><span>Dear Day</span><strong>planned with care</strong></div></div></div></section>
<section className="section who" id="who-we-are"><div className="wrap"><div className="section-title"><span className="eyebrow">Who we are</span><h2>مش مجرد مكان تشتري منه هدية.</h2></div><div className="who-grid"><div className="who-copy"><p><strong>Dear Day هي منصة لتخطيط وتنسيق المناسبات المهمة من البداية للنهاية.</strong> بنجمع عناصر اليوم اللي عادةً بتحتاج بحث وحجوزات منفصلة — المكان أو التجربة، الهدية، شكولاته و كيك، والورد — في تجربة واحدة تقدر تبنيها على ذوقك وميزانيتك.</p><p>الفكرة مش إننا نزود اختيارات أكتر؛ الفكرة إننا نقلل التشتت. نختار بعناية، نوضح التفاصيل، ونخلي كل عنصر في اليوم مكمل للعنصر اللي قبله.</p><p>بدأنا من القاهرة والجيزة، لكن Dear Day اتبنت من البداية كعلامة تقدر تكبر مع كل أنواع الأيام اللي تستحق اهتمام: عيد ميلاد، ذكرى، خطوبة، طلب زواج، أو حتى يوم بسيط عايز تخليه أميز.</p></div><div className="who-visual"><img src="/approved-pages/assets/home/experience-dinner.png" alt="تجربة عشاء منسقة ضمن Dear Day"/><div className="caption">من تفاصيل منفصلة إلى يوم واحد متناسق.</div></div></div></div></section>
<section className="purpose" aria-label="مهمة ورؤية Dear Day"><div className="wrap purpose-grid"><article className="purpose-card mission"><span className="purpose-label">Our mission</span><h2>مهمتنا</h2><p>نخلي ترتيب الأيام المهمة أبسط، أهدأ، وأكثر معنى؛ من خلال جمع التفاصيل في خطة واحدة منسقة حسب المناسبة والميزانية، باختيارات موثوقة وتجربة واضحة من أول الفكرة لحد اليوم نفسه.</p><span className="purpose-number" aria-hidden="true">01</span></article><article className="purpose-card vision"><span className="purpose-label">Our vision</span><h2>رؤيتنا</h2><p>أن تصبح Dear Day الوجهة الأولى في مصر لتخطيط وتنسيق المناسبات المهمة، من خلال تجربة متكاملة تجمع أفضل الاختيارات والخدمات في مكان واحد سهل، شخصي، وقابل للتخصيص.</p><span className="purpose-number" aria-hidden="true">02</span></article></div></section>
<section className="values" id="values"><div className="wrap"><div className="values-head"><span className="eyebrow">Our values</span><h2>القيم اللي بتوجّه كل تفصيلة</h2><p>هوية Dear Day مبنية على تجربة هادئة وإنسانية: اهتمام حقيقي، دفء بدون مبالغة، رقي بدون تعقيد، وتفاصيل تحس إنها معمولة لشخص بعينه.</p></div><div className="values-grid"><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="M12 20.2S4.8 15.8 3 10.9C1.7 7.5 3.8 4.7 6.9 4.7c2 0 3.6 1.1 5.1 3.1 1.5-2 3.1-3.1 5.1-3.1 3.1 0 5.2 2.8 3.9 6.2-1.8 4.9-9 9.3-9 9.3Z"></path></svg></div><small>Thoughtful</small><h3>الاهتمام</h3><p>كل اختيار له سبب. بنفكر في الشخص والمناسبة قبل ما نفكر في المنتج، ونخلي التفاصيل الصغيرة جزء من المعنى.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="M12 3v3M5.6 5.6l2.1 2.1M3 12h3m-.4 6.4 2.1-2.1M12 18v3m6.4-2.6-2.1-2.1M18 12h3m-2.6-6.4-2.1 2.1"></path><circle cx="12" cy="12" r="4"></circle></svg></div><small>Warm</small><h3>الدفء</h3><p>نخلي التجربة قريبة ومرحبة، من غير لغة أو صور مبالغ فيها. إحساس بسيط وصادق يليق بالأيام المهمة.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="m12 3 2.2 4.7L19 10l-4.8 2.3L12 17l-2.2-4.7L5 10l4.8-2.3L12 3Z"></path><path d="m19 16 .9 1.9L22 19l-2.1 1.1L19 22l-.9-1.9L16 19l2.1-1.1L19 16Z"></path></svg></div><small>Refined</small><h3>الرقي</h3><p>الرقي عندنا مش زحمة ولا فخامة مصطنعة. هو اختيار أحسن، وضوح أكتر، وتجربة مرتبة ومريحة بصريًا وعمليًا.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.2"></circle><path d="M5.5 20c.7-4 3-6.2 6.5-6.2s5.8 2.2 6.5 6.2"></path><path d="M4 9.5c-1.3.8-2 2-2 3.5M20 9.5c1.3.8 2 2 2 3.5"></path></svg></div><small>Human</small><h3>الإنسانية</h3><p>وراء كل حجز شخص بيحاول يقول حاجة لحد مهم بالنسبة له. بنصمم التجربة حوالين الناس، مش حوالين المعاملة نفسها.</p></article></div></div></section>
<section className="about-cta"><div className="wrap"><div className="cta-box"><div className="cta-copy"><span>Make the day matter</span><h2>عندك يوم مهم قريب؟</h2><p>ابدأ بالمناسبة والميزانية، وخلي Dear Day تجمع لك باقي التفاصيل.</p></div><Link className="cta-button" href={pathFor("occasions","ar")}>رتّب مناسبتي</Link></div></div></section>
</main>
  );
}
function EnglishAbout() {
  return (
<main id="main-content" className="dd-about-page" dir="ltr">
<section className="about-hero"><div className="wrap hero-grid"><div><span className="kicker">Our story</span><h1>The days that matter deserve real care.</h1><p>Dear Day started with a simple idea: planning a meaningful day should not mean chasing every detail separately. We bring the whole occasion into one clear, calm experience shaped around the person and the moment.</p></div><div className="hero-collage" aria-label="Details from the Dear Day experience"><img className="main-photo" src="/approved-pages/assets/media/complete-package.jpg" alt="A complete occasion setup by Dear Day"/><img className="small-photo" src="/approved-pages/assets/home/gift-flowers.png" alt="A thoughtfully selected flower bouquet"/><div className="brand-note"><span>Dear Day</span><strong>planned with care</strong></div></div></div></section>
<section className="section who" id="who-we-are"><div className="wrap"><div className="section-title"><span className="eyebrow">Who we are</span><h2>More than a place to buy a gift.</h2></div><div className="who-grid"><div className="who-copy"><p><strong>Dear Day is a platform for planning meaningful occasions from start to finish.</strong> We bring together the details that usually require separate searches and bookings — the venue or experience, gift, cake and sweets, and flowers — in one experience you can shape around your style and budget.</p><p>Our goal is not to overwhelm you with more options. It is to make the right options easier to find. We curate carefully, make the details clear, and help every part of the day feel connected.</p><p>We started in Cairo and Giza, but Dear Day was built to grow with every kind of day worth celebrating — a birthday, anniversary, engagement, proposal, or simply a day you want to make feel more special.</p></div><div className="who-visual"><img src="/approved-pages/assets/home/experience-dinner.png" alt="A curated dinner experience on Dear Day"/><div className="caption">From separate details to one beautifully connected day.</div></div></div></div></section>
<section className="purpose" aria-label="Dear Day mission and vision"><div className="wrap purpose-grid"><article className="purpose-card mission"><span className="purpose-label">Our mission</span><h2>Our mission</h2><p>To make meaningful occasions easier, calmer, and more personal by bringing every detail into one coordinated plan — shaped around the occasion and budget, with trusted choices and a clear experience from the first idea to the day itself.</p><span className="purpose-number" aria-hidden="true">01</span></article><article className="purpose-card vision"><span className="purpose-label">Our vision</span><h2>Our vision</h2><p>To become a leading destination in Egypt for planning meaningful occasions, with one seamless experience that brings trusted services and thoughtful choices together in a way that feels simple, personal, and easy to tailor.</p><span className="purpose-number" aria-hidden="true">02</span></article></div></section>
<section className="values" id="values"><div className="wrap"><div className="values-head"><span className="eyebrow">Our values</span><h2>The values behind every detail</h2><p>Dear Day is built around a calm, human experience: genuine thoughtfulness, warmth without excess, refinement without complication, and details that feel personal rather than generic.</p></div><div className="values-grid"><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="M12 20.2S4.8 15.8 3 10.9C1.7 7.5 3.8 4.7 6.9 4.7c2 0 3.6 1.1 5.1 3.1 1.5-2 3.1-3.1 5.1-3.1 3.1 0 5.2 2.8 3.9 6.2-1.8 4.9-9 9.3-9 9.3Z"></path></svg></div><small>Thoughtful</small><h3>Thoughtfulness</h3><p>Every choice should have a reason. We start with the person and the occasion, not the product, and make the small details part of the meaning.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="M12 3v3M5.6 5.6l2.1 2.1M3 12h3m-.4 6.4 2.1-2.1M12 18v3m6.4-2.6-2.1-2.1M18 12h3m-2.6-6.4-2.1 2.1"></path><circle cx="12" cy="12" r="4"></circle></svg></div><small>Warm</small><h3>Warmth</h3><p>We keep the experience welcoming and genuine, without overdone language or imagery. Simple, sincere, and right for the moments that matter.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><path d="m12 3 2.2 4.7L19 10l-4.8 2.3L12 17l-2.2-4.7L5 10l4.8-2.3L12 3Z"></path><path d="m19 16 .9 1.9L22 19l-2.1 1.1L19 22l-.9-1.9L16 19l2.1-1.1L19 16Z"></path></svg></div><small>Refined</small><h3>Refinement</h3><p>For us, refinement is not about excess. It means better choices, more clarity, and an experience that feels considered both visually and practically.</p></article><article className="value"><div className="value-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.2"></circle><path d="M5.5 20c.7-4 3-6.2 6.5-6.2s5.8 2.2 6.5 6.2"></path><path d="M4 9.5c-1.3.8-2 2-2 3.5M20 9.5c1.3.8 2 2 2 3.5"></path></svg></div><small>Human</small><h3>Humanity</h3><p>Behind every booking is a person trying to make someone important feel something. We design the experience around people, not the transaction.</p></article></div></div></section>
<section className="about-cta"><div className="wrap"><div className="cta-box"><div className="cta-copy"><span>Make the day matter</span><h2>Have an important day coming up?</h2><p>Start with the occasion and your budget, and let Dear Day bring the rest of the details together.</p></div><Link className="cta-button" href={pathFor("occasions","en")}>Plan My Occasion</Link></div></div></section>
</main>
  );
}
export default function AboutPage({locale="ar"}) {
  return locale==="en"?<EnglishAbout/>:<ArabicAbout/>;
}
