import Link from "next/link";
import { pathFor } from "../lib/locales";

// Informational page only: requests remain in the existing authenticated account flow.
export default function DeleteAccountPage({ locale }) {
 return locale === "en" ? (
<main id="main-content" className="dd-main dd-legal-page dd-deletion-page" dir="ltr"><section className="legal-hero"><div className="wrap"><span className="eyebrow">Privacy & control</span><h1>Account & Data Deletion</h1><p>You can request deletion of your Dear Day account and personal data associated with it. This page explains how to submit a request and what happens after your identity is verified.</p></div></section><div className="wrap content"><article className="legal-card"><div className="intro-note">These instructions also apply if you created or accessed your Dear Day account using Facebook or another social sign-in provider.</div>
<section className="legal-section"><h2>1. How to request deletion</h2><ol><li>Sign in to your Dear Day account.</li><li>Open <Link href={pathFor("account", locale)}>My Account</Link>.</li><li>Go to <strong>Account & data deletion</strong> and choose <strong>Request account deletion</strong>.</li><li>Your request is recorded and a Super Admin is notified for review.</li><li>If approved, Dear Day permanently removes the sign-in account and personal profile data and de-identifies historical records that must be retained for operational, accounting, legal, refund, or dispute purposes.</li></ol><Link className="cta" href={pathFor("account", locale)}>Open My Account</Link></section>
<section className="legal-section"><h2>2. What data is deleted?</h2><p>After verification, we delete or de-identify personal data that is no longer needed to provide the service. This may include account details, contact information, preferences, and data associated with your use of Dear Day.</p></section>
<section className="legal-section"><h2>3. Data we may need to retain</h2><p>We may retain limited records where required to comply with legal or accounting obligations, protect legal rights, or resolve an active order, refund, charge, or dispute. Data retained for these purposes is not used for marketing.</p></section>
<section className="legal-section"><h2>4. Facebook Login</h2><p>If you used Facebook to create or access your Dear Day account, follow the same steps above to request deletion of data held by Dear Day. Removing Dear Day from your Facebook settings by itself does not automatically submit a deletion request for data stored by Dear Day.</p></section>
<section className="legal-section"><h2>5. Privacy questions</h2><p>For more information about how Dear Day handles personal data, see our <Link href={pathFor("privacy", locale)}>Privacy Policy</Link>.</p><p className="small">Last updated: October 3, 2026</p></section>
</article></div></main>
 ) : (
<main id="main-content" className="dd-main dd-legal-page dd-deletion-page" dir="rtl"><section className="legal-hero"><div className="wrap"><span className="eyebrow">خصوصيتك وتحكمك في بياناتك</span><h1>حذف الحساب والبيانات</h1><p>يمكنك طلب حذف حساب Dear Day والبيانات الشخصية المرتبطة به. توضح هذه الصفحة طريقة تقديم الطلب وما يحدث للبيانات بعد التحقق منه.</p></div></section><div className="wrap content"><article className="legal-card"><div className="intro-note">هذه الصفحة مخصصة أيضًا للمستخدمين الذين سجلوا الدخول إلى Dear Day باستخدام Facebook أو أي مزود تسجيل دخول اجتماعي آخر.</div>
<section className="legal-section"><h2>1. كيفية طلب حذف بياناتك</h2><ol><li>سجّل الدخول إلى حساب Dear Day.</li><li>افتح صفحة <Link href={pathFor("account", locale)}>حسابي</Link>.</li><li>انتقل إلى قسم <strong>حذف الحساب والبيانات</strong> واضغط <strong>طلب حذف الحساب</strong>.</li><li>يتم تسجيل الطلب وإرسال إشعار للسوبر أدمن لمراجعته.</li><li>عند الموافقة، يحذف Dear Day حساب تسجيل الدخول وبيانات الملف الشخصي نهائيًا، ويتم فصل السجلات التاريخية التي يلزم الاحتفاظ بها تشغيليًا أو محاسبيًا أو قانونيًا أو لتسوية استرداد أو نزاع عن هوية العميل.</li></ol><Link className="cta" href={pathFor("account", locale)}>فتح حسابي</Link></section>
<section className="legal-section"><h2>2. ما الذي يتم حذفه؟</h2><p>بعد التحقق من الطلب، نحذف أو نفصل عن هويتك البيانات الشخصية التي لم نعد بحاجة إليها لتقديم الخدمة، وقد يشمل ذلك بيانات الحساب والتواصل والتفضيلات والبيانات المرتبطة باستخدام المنصة.</p></section>
<section className="legal-section"><h2>3. بيانات قد نحتاج للاحتفاظ بها</h2><p>قد نحتفظ ببعض السجلات بالحد الأدنى عندما يكون ذلك ضروريًا للامتثال لالتزام قانوني أو محاسبي، أو لحماية الحقوق، أو لتسوية طلب أو استرداد أو نزاع قائم. لا تُستخدم هذه البيانات المحتفظ بها لأغراض تسويقية.</p></section>
<section className="legal-section"><h2>4. تسجيل الدخول عبر Facebook</h2><p>إذا استخدمت Facebook لإنشاء حساب أو تسجيل الدخول إلى Dear Day، يمكنك استخدام نفس الخطوات أعلاه لطلب حذف البيانات التي تحتفظ بها Dear Day. إزالة Dear Day من إعدادات Facebook وحدها لا تُعد تلقائيًا طلب حذف للبيانات المخزنة لدينا.</p></section>
<section className="legal-section"><h2>5. أسئلة عن الخصوصية</h2><p>للمزيد حول أنواع البيانات التي نجمعها واستخدامها، راجع <Link href={pathFor("privacy", locale)}>سياسة الخصوصية</Link>.</p><p className="small">آخر تحديث: 3 أكتوبر 2026</p></section>
</article></div></main>
 );
}
