import Link from "next/link";
import { pathFor } from "../lib/locales";

// Approved production wording preserved during the React migration (2026-10-09).
export default function TermsPage({ locale }) {
  return locale === "en" ? (
<main id="main-content" className="dd-main dd-legal-page" dir="ltr"><section className="legal-hero"><div className="wrap"><span className="eyebrow">Using Dear Day</span><h1>Terms & Conditions</h1><p>These Terms govern the use of the Dear Day platform, including account creation, selecting products and services, bookings, payments, and interactions with service providers and partners.</p><span className="updated">Last updated: October 2, 2026</span></div></section>
<div className="wrap legal-layout"><aside className="toc" aria-label="Terms and conditions contents"><strong>On this page</strong><a href="#acceptance">Acceptance of Terms</a><a href="#platform">Nature of the Platform</a><a href="#account">Account Creation & Use</a><a href="#orders">Orders & Bookings</a><a href="#prices">Prices & Payment</a><a href="#partners">Partner Products & Services</a><a href="#changes">Availability, Changes & Substitutions</a><a href="#refunds">Cancellation & Refunds</a><a href="#delivery">Delivery & Timing</a><a href="#conduct">Acceptable Use</a><a href="#ip">Intellectual Property</a><a href="#liability">Limitations of Liability</a><a href="#force">Events Outside Reasonable Control</a><a href="#law">Governing Law & Disputes</a><a href="#updates">Changes to These Terms</a><a href="#contact">Contact Us</a></aside><article className="legal-card"><div className="intro-note">By using Dear Day, creating an account, or completing an order or booking, you agree to these Terms to the extent permitted by the laws and regulations applicable in the Arab Republic of Egypt. Nothing in these Terms is intended to remove any mandatory consumer right that cannot legally be waived.</div>
<section className="legal-section" id="acceptance"><h2>1. Acceptance of Terms</h2><p>These Terms govern your use of the Dear Day website and its related digital services. If you do not agree to these Terms, please do not complete an order or booking.</p><p>Additional terms may apply to certain services, offers or bookings. Where relevant, those terms will be shown to you before confirmation.</p></section>

<section className="legal-section" id="platform"><h2>2. Nature of the Dear Day Platform</h2><p>Dear Day is a digital platform that helps users discover, select, arrange and book products and services for occasions. Some products or services may be provided directly by Dear Day, while others are provided by independent partners such as gift and cake shops, venues and experience providers, and occasion-planning service providers.</p><p>Where a service is provided by an independent partner, Dear Day may facilitate the listing of the service, receipt of the order, coordination, payment or support depending on the nature of the service, while the partner remains responsible for delivering its product or service in accordance with the confirmed details.</p></section>

<section className="legal-section" id="account"><h2>3. Account Creation & Use</h2><ul><li>You must provide accurate and up-to-date information when creating an account or placing an order.</li><li>You are responsible for keeping your login credentials confidential and must not share them with others.</li><li>You should notify Dear Day if you suspect any unauthorised use of your account.</li><li>We may suspend or restrict an account if we identify fraudulent, abusive, unlawful use or use that breaches these Terms.</li></ul></section>

<section className="legal-section" id="orders"><h2>4. Orders & Bookings</h2><p>Submitting an order through the platform means that Dear Day has received your request, but it does not always mean that the booking is final where the service requires availability confirmation from the service provider.</p><p>An order or booking becomes confirmed when a confirmation status appears on the platform or a confirmation notice is sent to the user, depending on the nature of the service.</p><p>You are responsible for reviewing the order details before confirmation, including the date, area, selected products or services, quantities and any customisations you have entered.</p><p>A single order may include more than one product or service from more than one partner. Different items within the same order may therefore be subject to different cancellation and refund terms depending on the nature of each item and the policy shown for it before the order is confirmed.</p></section>

<section className="legal-section" id="prices"><h2>5. Prices & Payment</h2><p>Dear Day displays the price available at the time of the order. Any additional charges, such as delivery or service fees, must be shown before payment is completed where they apply.</p><p>Payments may be processed through approved electronic payment service providers. Payment processing is also subject to the technical and security requirements of the relevant payment provider.</p><p>If there is a clear technical error in a price or product description before the order is confirmed, Dear Day may correct the error and inform the user before the order is fulfilled, while providing the options required under applicable law and policy.</p></section>

<section className="legal-section" id="partners"><h2>6. Products & Services Provided by Partners</h2><p>Partners are required to provide a reasonable and accurate description of their products or services, comply with the material specifications agreed for the order, and maintain any licences or requirements needed for their activity where required by law.</p><p>Minor details in handmade or natural products, such as colour shades, flower arrangements or decorative elements, may differ from the images shown, provided that such differences do not unreasonably change the essential nature or value of the order.</p><div className="important"><strong>Important:</strong> Any additional arrangement made directly between a user and a partner outside Dear Day, and not documented through the platform or official support channels, is not considered part of the order confirmed through Dear Day.</div></section>

<section className="legal-section" id="changes"><h2>7. Availability, Changes & Substitutions</h2><p>Some products and services depend on the partner’s actual availability. If an item becomes unavailable after an order is placed, we will contact the user to offer an appropriate alternative, modification or cancellation of the affected part, depending on the nature of the order and the user’s applicable legal rights.</p><p>A material substitution to a product or service must not be made without informing the user and obtaining their consent where such consent is required.</p></section>

<section className="legal-section" id="refunds"><h2>8. Cancellation & Refunds</h2><p>Cancellation and refund rules vary depending on the nature of the product or service and the stage of fulfilment. Certain customised or perishable products, or bookings tied to a specific date or time, may be subject to special rules.</p><p>Dear Day sets the general framework for cancellation and refund policies. A partner may select an approved policy for its services or propose an exception for a specific product or service, but that policy or exception does not become effective on the platform until it has been approved in accordance with Dear Day’s procedures.</p><p>If an order contains more than one item, the refund percentage or conditions may differ from one item to another. Where an item is subject to a specific policy, the applicable terms will be shown to the user before the order is confirmed.</p><div className="important"><strong>Reference policy for the order:</strong> The policy displayed and applicable to an item at the time the order is confirmed is the reference policy for that item. Any later change to a partner or product policy does not apply retroactively to orders that were already confirmed, while mandatory consumer rights remain fully applicable.</div><p>For more information, please see our <Link href={pathFor("refunds", locale)}>Cancellation & Refund Policy</Link>.</p><p>Consumer rights provided under Egyptian law remain applicable, including where the law provides a right to replacement or reimbursement.</p></section>

<section className="legal-section" id="delivery"><h2>9. Delivery & Timing</h2><p>Dear Day and its partners make reasonable efforts to meet confirmed or estimated delivery and service times. Some orders may nevertheless be affected by operational, traffic or logistical factors outside their direct control.</p><p>If a material delay occurs, the user may contact support so the situation can be assessed based on the nature of the order, the applicable Cancellation & Refund Policy, and the user’s legal rights.</p></section>

<section className="legal-section" id="conduct"><h2>10. Acceptable Use of the Platform</h2><p>Dear Day must not be used for any unlawful or fraudulent activity or in any way that harms the platform, its users or its partners. This includes, for example, attempting to compromise the platform, misusing payment systems, intentionally providing misleading information, or using platform content for unauthorised commercial purposes.</p></section>

<section className="legal-section" id="ip"><h2>11. Intellectual Property</h2><p>Rights in the Dear Day brand, platform design, interface, original content, graphics and software belong to Dear Day or to the relevant rights holders that have licensed them to Dear Day, as applicable.</p><p>Trademarks, images and content owned by partners remain the property of their respective owners and are displayed under the licences or arrangements granted to Dear Day.</p><p>Platform content may not be copied, republished or commercially exploited without prior written permission where such permission is required.</p></section>

<section className="legal-section" id="liability"><h2>12. Limitations of Liability</h2><p>Dear Day is responsible for its direct obligations in operating the platform, coordinating services and providing support to the extent required by law. Where a product or service is provided by an independent partner, that partner is responsible for the actual fulfilment and quality of the product or service it provides, while Dear Day remains available to help address issues in accordance with these Terms and the applicable policies.</p><p>To the extent permitted by law, Dear Day is not liable for indirect or consequential losses that are not a direct and reasonably foreseeable result of a breach by Dear Day.</p><p>Nothing in these Terms excludes or limits any liability that cannot legally be excluded or limited.</p></section>

<section className="legal-section" id="force"><h2>13. Events Outside Reasonable Control</h2><p>Some orders or bookings may be affected by circumstances that cannot reasonably be controlled, such as government decisions, disasters, major accidents, unexpected closures, widespread service outages, severe weather conditions or similar events.</p><p>In such cases, we will seek to minimise the impact of the event and communicate with the user about available alternatives where reasonably possible.</p></section>

<section className="legal-section" id="law"><h2>14. Governing Law & Dispute Resolution</h2><p>These Terms are governed by the laws applicable in the Arab Republic of Egypt, including relevant consumer-protection rules.</p><p>If an issue arises, we encourage users to contact Dear Day Customer Support first so that we can try to resolve it. This does not affect the consumer’s right to contact the Consumer Protection Agency, other competent authorities, or the courts as provided by law.</p></section>

<section className="legal-section" id="updates"><h2>15. Changes to These Terms</h2><p>We may update these Terms from time to time to reflect changes to the platform or legal or operational requirements. The updated version will be published on this page together with the date of the latest update.</p><p>Changes will not apply retroactively to confirmed orders where doing so would affect rights already acquired by the user, except to the extent permitted by law.</p></section>

<section className="legal-section" id="contact"><h2>16. Contact Us</h2><p>If you have a question about these Terms or an existing order, you can contact Dear Day through our <Link href={pathFor("contact", locale)}>Contact Us</Link> page or through the official customer-support channels displayed on the platform.</p></section>
</article></div></main>
  ) : (
<main id="main-content" className="dd-main dd-legal-page" dir="rtl">
<section className="legal-hero"><div className="wrap"><span className="eyebrow">استخدام Dear Day</span><h1>الشروط والأحكام</h1><p>تنظم هذه الشروط استخدام منصة Dear Day، بما يشمل إنشاء الحسابات، واختيار المنتجات والخدمات، والحجوزات، والدفع، والتعامل مع مقدمي الخدمات والشركاء.</p><span className="updated">آخر تحديث: 2 أكتوبر 2026</span></div></section>

<div className="wrap legal-layout">
<aside className="toc" aria-label="محتويات الشروط والأحكام"><strong>محتويات الصفحة</strong><a href="#acceptance">قبول الشروط</a><a href="#platform">طبيعة المنصة</a><a href="#account">الحسابات</a><a href="#orders">الطلبات والحجوزات</a><a href="#prices">الأسعار والدفع</a><a href="#partners">الشركاء</a><a href="#changes">التعديلات والتوافر</a><a href="#refunds">الإلغاء والاسترداد</a><a href="#delivery">التوصيل والمواعيد</a><a href="#conduct">الاستخدام المقبول</a><a href="#ip">الملكية الفكرية</a><a href="#liability">حدود المسؤولية</a><a href="#force">الظروف الخارجة عن السيطرة</a><a href="#law">القانون والنزاعات</a><a href="#updates">تعديل الشروط</a><a href="#contact">التواصل معنا</a></aside>
<article className="legal-card">
<div className="intro-note">باستخدامك Dear Day أو إنشاء حساب أو إتمام طلب أو حجز، فإنك توافق على هذه الشروط بالقدر الذي تسمح به القوانين واللوائح المعمول بها في جمهورية مصر العربية. لا تهدف أي فقرة في هذه الشروط إلى إلغاء حق قانوني إلزامي للمستهلك لا يجوز التنازل عنه.</div>

<section className="legal-section" id="acceptance"><h2>1. قبول الشروط</h2><p>تحكم هذه الشروط استخدام موقع Dear Day والخدمات الرقمية المرتبطة به. إذا كنت لا توافق على هذه الشروط، يرجى عدم إتمام الطلب أو الحجز.</p><p>قد تطبق شروط إضافية على بعض الخدمات أو العروض أو الحجوزات، وسيتم إظهارها للمستخدم قبل التأكيد متى كانت ذات صلة.</p></section>


<section className="legal-section" id="platform"><h2>2. طبيعة منصة Dear Day</h2><p>Dear Day منصة رقمية تساعد المستخدم على اكتشاف واختيار وترتيب وحجز منتجات وخدمات مرتبطة بالمناسبات، وقد تكون بعض المنتجات أو الخدمات مقدمة مباشرة من Dear Day، بينما يقدم البعض الآخر شركاء مستقلون مثل محلات الهدايا والكيك، والأماكن والتجارب، ومقدمي خدمات تنظيم المناسبات.</p><p>عندما تكون الخدمة مقدمة من شريك مستقل، تعمل Dear Day على تسهيل عرض الخدمة، واستقبال الطلب، والتنسيق، والدفع أو الدعم بحسب طبيعة الخدمة، بينما يظل الشريك مسؤولًا عن تنفيذ المنتج أو الخدمة الخاصة به وفق التفاصيل المؤكدة.</p></section>


<section className="legal-section" id="account"><h2>3. إنشاء الحساب واستخدامه</h2><ul><li>يجب تقديم بيانات صحيحة وحديثة عند إنشاء الحساب أو إتمام الطلب.</li><li>يتحمل المستخدم مسؤولية الحفاظ على سرية بيانات الدخول وعدم مشاركتها مع الغير.</li><li>يجب إخطار Dear Day عند الاشتباه في استخدام غير مصرح به للحساب.</li><li>يجوز لنا تعليق أو تقييد الحساب إذا وجدنا استخدامًا احتياليًا أو مسيئًا أو مخالفًا للقانون أو لهذه الشروط.</li></ul></section>


<section className="legal-section" id="orders"><h2>4. الطلبات والحجوزات</h2><p>إرسال الطلب عبر المنصة يعني استلام Dear Day لطلبك، لكنه لا يعني دائمًا أن الحجز أصبح نهائيًا إذا كانت الخدمة تتطلب تأكيد التوافر من مقدم الخدمة.</p><p>يصبح الطلب أو الحجز مؤكدًا عندما تظهر حالة التأكيد على المنصة أو يتم إرسال إشعار تأكيد للمستخدم، بحسب طبيعة الخدمة.</p><p>يلتزم المستخدم بمراجعة تفاصيل الطلب قبل التأكيد، بما في ذلك التاريخ، والمنطقة، والمنتجات أو الخدمات المختارة، والكميات، وأي تخصيصات تم إدخالها.</p><p>قد يضم الطلب الواحد أكثر من منتج أو خدمة من أكثر من شريك، ويجوز أن تخضع عناصر الطلب المختلفة لشروط إلغاء واسترداد مختلفة بحسب طبيعة كل عنصر والسياسة المعروضة له قبل تأكيد الطلب.</p></section>


<section className="legal-section" id="prices"><h2>5. الأسعار والدفع</h2><p>تعرض Dear Day السعر المتاح وقت الطلب، وأي رسوم إضافية مثل رسوم التوصيل أو الخدمة يجب أن تظهر قبل إتمام الدفع عندما تكون مطبقة.</p><p>قد تتم معالجة المدفوعات من خلال مزودي دفع إلكتروني معتمدين. وتخضع عملية الدفع أيضًا للشروط الفنية والأمنية الخاصة بمزود الدفع.</p><p>في حالة حدوث خطأ تقني واضح في السعر أو وصف المنتج قبل تأكيد الطلب، يحق لـ Dear Day تصحيح الخطأ وإبلاغ المستخدم قبل تنفيذ الطلب، مع إتاحة الخيارات التي يقررها القانون والسياسة المعمول بها.</p></section>


<section className="legal-section" id="partners"><h2>6. المنتجات والخدمات المقدمة من الشركاء</h2><p>يلتزم الشريك بتقديم وصف صحيح ومعقول للمنتج أو الخدمة، والالتزام بالمواصفات الجوهرية المتفق عليها، وتوفير التراخيص أو الاشتراطات اللازمة لنشاطه متى كانت مطلوبة قانونًا.</p><p>قد تختلف بعض التفاصيل البسيطة في المنتجات اليدوية أو الطبيعية، مثل درجات الألوان أو تنسيق الزهور أو الزخارف، عن الصور المعروضة، بشرط ألا يغيّر ذلك الطبيعة الجوهرية للطلب أو قيمته بشكل غير مبرر.</p><div className="important"><strong>مهم:</strong> أي اتفاق إضافي يتم بين المستخدم والشريك خارج Dear Day ولم يتم توثيقه عبر المنصة أو قنوات الدعم الرسمية لا يُعد جزءًا من الطلب المؤكد على Dear Day.</div></section>


<section className="legal-section" id="changes"><h2>7. التوافر والتعديلات والاستبدال</h2><p>تعتمد بعض المنتجات والخدمات على التوافر الفعلي لدى الشريك. إذا تعذر توفير عنصر بعد الطلب، سنتواصل مع المستخدم لعرض بديل مناسب أو تعديل أو إلغاء الجزء المتأثر وفقًا لطبيعة الطلب والحقوق القانونية المقررة.</p><p>لا يجوز إجراء استبدال جوهري في المنتج أو الخدمة دون إخطار المستخدم والحصول على موافقته عندما يكون ذلك مطلوبًا.</p></section>


<section className="legal-section" id="refunds"><h2>8. الإلغاء والاسترداد</h2><p>تختلف قواعد الإلغاء والاسترداد حسب طبيعة المنتج أو الخدمة ومرحلة التنفيذ. بعض المنتجات المخصصة أو القابلة للتلف أو الحجوزات المرتبطة بموعد محدد قد تخضع لقواعد خاصة.</p><p>تحدد Dear Day الإطار العام لسياسات الإلغاء والاسترداد. ويجوز للشريك اختيار سياسة منظمة لخدماته أو اقتراح استثناء لمنتج أو خدمة محددة، ولا تصبح هذه السياسة أو الاستثناء نافذًا على المنصة إلا بعد اعتماده وفق إجراءات Dear Day.</p><p>إذا كان الطلب يحتوي على أكثر من عنصر، فقد تختلف نسبة أو شروط الاسترداد من عنصر إلى آخر. ويُعرض للمستخدم قبل تأكيد الطلب ما ينطبق على العناصر التي لها سياسة خاصة متى كانت مطبقة.</p><div className="important"><strong>السياسة المرجعية للطلب:</strong> السياسة التي كانت معروضة ومطبقة على العنصر وقت تأكيد الطلب هي المرجع لذلك العنصر. أي تعديل لاحق على سياسة الشريك أو المنتج لا يطبق بأثر رجعي على الطلبات المؤكدة سابقًا، مع بقاء الحقوق القانونية الإلزامية للمستهلك واجبة التطبيق.</div><p>للتفاصيل راجع <Link href={pathFor("refunds", locale)}>سياسة الإلغاء والاسترداد</Link>.</p><p>تظل حقوق المستهلك التي يقررها القانون المصري واجبة التطبيق، بما في ذلك الحالات التي يقرر فيها القانون حق الاستبدال أو رد القيمة.</p></section>


<section className="legal-section" id="delivery"><h2>9. التوصيل والمواعيد</h2><p>تبذل Dear Day والشركاء جهودًا معقولة للالتزام بالمواعيد المحددة أو التقديرية. وقد تتأثر بعض الطلبات بعوامل تشغيلية أو مرورية أو لوجستية خارج نطاق السيطرة المباشرة.</p><p>إذا حدث تأخير جوهري، يمكن للمستخدم التواصل مع الدعم ليتم تقييم الحالة وفق طبيعة الطلب وسياسة الإلغاء والاسترداد والحقوق المقررة قانونًا.</p></section>


<section className="legal-section" id="conduct"><h2>10. الاستخدام المقبول للمنصة</h2><p>يحظر استخدام Dear Day في أي نشاط غير قانوني أو احتيالي أو يضر بالمنصة أو مستخدميها أو شركائها. ويشمل ذلك، على سبيل المثال، محاولة اختراق المنصة، أو إساءة استخدام أنظمة الدفع، أو تقديم بيانات مضللة عمدًا، أو استخدام المحتوى لأغراض تجارية غير مصرح بها.</p></section>


<section className="legal-section" id="ip"><h2>11. الملكية الفكرية</h2><p>تعود حقوق Dear Day في العلامة التجارية، وتصميم المنصة، والواجهة، والمحتوى الأصلي، والرسومات، والبرمجيات، إلى Dear Day أو إلى أصحاب الحقوق المرخصين لها بحسب الحالة.</p><p>تظل العلامات التجارية والصور والمحتويات المملوكة للشركاء مملوكة لأصحابها، ويتم عرضها وفق التراخيص أو التفاهمات الممنوحة لـ Dear Day.</p><p>لا يجوز نسخ أو إعادة نشر أو استغلال محتوى المنصة تجاريًا دون إذن كتابي مسبق حيث يلزم.</p></section>


<section className="legal-section" id="liability"><h2>12. حدود المسؤولية</h2><p>تتحمل Dear Day المسؤولية عن التزاماتها المباشرة في تشغيل المنصة والتنسيق والدعم بالقدر المقرر قانونًا. وعندما يكون المنتج أو الخدمة مقدمة من شريك مستقل، يتحمل الشريك مسؤولية التنفيذ الفعلي وجودة المنتج أو الخدمة التي يقدمها، مع بقاء دور Dear Day في المساعدة على معالجة المشكلة وفق هذه الشروط والسياسات المعمول بها.</p><p>وفي الحدود التي يسمح بها القانون، لا تتحمل Dear Day الخسائر غير المباشرة أو التبعية التي لا تكون نتيجة مباشرة ومعقولة لإخلال من جانبها.</p><p>لا تستبعد هذه الشروط أي مسؤولية لا يجوز قانونًا استبعادها أو الحد منها.</p></section>


<section className="legal-section" id="force"><h2>13. الظروف الخارجة عن السيطرة</h2><p>قد تتأثر بعض الطلبات أو الحجوزات بظروف لا يمكن السيطرة عليها بصورة معقولة، مثل القرارات الحكومية، أو الكوارث، أو الحوادث الجسيمة، أو الإغلاقات غير المتوقعة، أو الانقطاعات الواسعة في الخدمات، أو الظروف الجوية الشديدة، أو أحداث مشابهة.</p><p>في هذه الحالات سنحاول تقليل أثر الحدث والتواصل مع المستخدم بشأن البدائل المتاحة متى كان ذلك ممكنًا.</p></section>


<section className="legal-section" id="law"><h2>14. القانون المطبق وتسوية النزاعات</h2><p>تخضع هذه الشروط للقوانين السارية في جمهورية مصر العربية، بما في ذلك قواعد حماية المستهلك ذات الصلة.</p><p>في حالة وجود مشكلة، نشجع المستخدم على التواصل أولًا مع خدمة عملاء Dear Day لمحاولة حلها. ولا يؤثر ذلك على حق المستهلك في اللجوء إلى جهاز حماية المستهلك أو الجهات المختصة أو القضاء بحسب ما يقرره القانون.</p></section>


<section className="legal-section" id="updates"><h2>15. تعديل الشروط</h2><p>يجوز تحديث هذه الشروط من وقت لآخر لتتوافق مع تطوير المنصة أو المتطلبات القانونية أو التشغيلية. سيتم نشر النسخة المحدثة على هذه الصفحة مع توضيح تاريخ آخر تحديث.</p><p>لا تطبق التعديلات بأثر رجعي على الطلبات المؤكدة إذا كان ذلك يمس حقوقًا مكتسبة للمستخدم، إلا في الحدود التي يجيزها القانون.</p></section>


<section className="legal-section" id="contact"><h2>16. التواصل معنا</h2><p>لأي استفسار عن هذه الشروط أو عن طلب قائم، يمكن التواصل مع Dear Day من خلال صفحة <Link href={pathFor("contact", locale)}>تواصل معنا</Link> أو قنوات خدمة العملاء الرسمية المعروضة على المنصة.</p></section>

</article>
</div>
</main>
  );
}
