-- Harden Partner Portal RPCs: privileged logic lives in private schema;
-- public RPC endpoints run as SECURITY INVOKER.

grant usage on schema private to authenticated;

create or replace function private.partner_submit_listing_impl(
 p_listing_id uuid,p_partner_id uuid,p_category_id uuid,p_kind public.listing_kind,
 p_name_ar text,p_name_en text,p_description_ar text,p_description_en text,
 p_price numeric,p_compare_at_price numeric,p_currency text,p_media jsonb,
 p_is_available boolean,p_stock_qty integer,p_capacity_per_day integer,p_submit boolean default true
) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_uid uuid:=auth.uid();v_listing_id uuid;v_version_id uuid;v_status public.listing_status;v_existing_partner uuid;
begin
 if v_uid is null then raise exception 'Authentication required' using errcode='42501';end if;
 if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_active=true and p.role='partner_user') then raise exception 'Partner access required' using errcode='42501';end if;
 if not exists(select 1 from public.partner_users pu join public.partners p on p.id=pu.partner_id where pu.user_id=v_uid and pu.partner_id=p_partner_id and pu.is_active=true and p.status='active') then raise exception 'Partner membership is not active' using errcode='42501';end if;
 if nullif(trim(p_name_ar),'') is null then raise exception 'Arabic name is required';end if;
 if coalesce(p_price,0)<0 then raise exception 'Price cannot be negative';end if;
 if p_compare_at_price is not null and p_compare_at_price<0 then raise exception 'Compare price cannot be negative';end if;
 if p_media is not null and jsonb_typeof(p_media)<>'array' then raise exception 'Media must be a JSON array';end if;
 v_status:=case when p_submit then 'pending_review'::public.listing_status else 'draft'::public.listing_status end;
 if p_listing_id is null then insert into public.listings(partner_id,category_id,kind,is_available,stock_qty,capacity_per_day) values(p_partner_id,p_category_id,p_kind,false,null,null) returning id into v_listing_id;
 else select l.partner_id into v_existing_partner from public.listings l where l.id=p_listing_id;if v_existing_partner is null then raise exception 'Listing not found';end if;if v_existing_partner<>p_partner_id then raise exception 'Listing does not belong to this partner' using errcode='42501';end if;v_listing_id:=p_listing_id;end if;
 if p_submit and exists(select 1 from public.listing_versions lv where lv.listing_id=v_listing_id and lv.status='pending_review') then raise exception 'This listing already has a version pending review';end if;
 insert into public.listing_versions(listing_id,status,name_ar,name_en,description_ar,description_en,price,compare_at_price,currency,media,metadata,submitted_by,submitted_at)
 values(v_listing_id,v_status,trim(p_name_ar),nullif(trim(p_name_en),''),nullif(trim(p_description_ar),''),nullif(trim(p_description_en),''),coalesce(p_price,0),p_compare_at_price,coalesce(nullif(trim(p_currency),''),'EGP'),coalesce(p_media,'[]'::jsonb),jsonb_build_object('source','partner','proposed',jsonb_build_object('partner_id',p_partner_id,'category_id',p_category_id,'kind',p_kind,'is_available',coalesce(p_is_available,true),'stock_qty',p_stock_qty,'capacity_per_day',p_capacity_per_day)),case when p_submit then v_uid else null end,case when p_submit then now() else null end) returning id into v_version_id;
 insert into public.audit_logs(actor_id,action,entity_type,entity_id,after_data) values(v_uid,case when p_submit then 'partner_listing_submitted' else 'partner_listing_draft_created' end,'listing',v_listing_id::text,jsonb_build_object('version_id',v_version_id,'status',v_status,'partner_id',p_partner_id));
 return jsonb_build_object('listing_id',v_listing_id,'version_id',v_version_id,'status',v_status);
end;$$;

create or replace function private.partner_set_inventory_impl(p_listing_id uuid,p_is_available boolean,p_stock_qty integer,p_capacity_per_day integer)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_uid uuid:=auth.uid();v_listing public.listings%rowtype;
begin if v_uid is null then raise exception 'Authentication required' using errcode='42501';end if;select l.* into v_listing from public.listings l where l.id=p_listing_id;if v_listing.id is null or not exists(select 1 from public.partner_users pu where pu.partner_id=v_listing.partner_id and pu.user_id=v_uid and pu.is_active=true) then raise exception 'Listing access denied' using errcode='42501';end if;update public.listings set is_available=coalesce(p_is_available,is_available),stock_qty=p_stock_qty,capacity_per_day=p_capacity_per_day,updated_at=now() where id=p_listing_id;insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(v_uid,'partner_inventory_updated','listing',p_listing_id::text,jsonb_build_object('is_available',v_listing.is_available,'stock_qty',v_listing.stock_qty,'capacity_per_day',v_listing.capacity_per_day),jsonb_build_object('is_available',p_is_available,'stock_qty',p_stock_qty,'capacity_per_day',p_capacity_per_day));return jsonb_build_object('listing_id',p_listing_id,'updated',true);end;$$;

create or replace function private.partner_get_order_detail_impl(p_partner_order_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_uid uuid:=auth.uid();v_po public.partner_orders%rowtype;v_order jsonb;v_items jsonb;
begin if v_uid is null then raise exception 'Authentication required' using errcode='42501';end if;select po.* into v_po from public.partner_orders po where po.id=p_partner_order_id;if v_po.id is null or not exists(select 1 from public.partner_users pu where pu.partner_id=v_po.partner_id and pu.user_id=v_uid and pu.is_active=true) then raise exception 'Partner order access denied' using errcode='42501';end if;select jsonb_build_object('order_number',o.order_number,'occasion_type',o.occasion_type,'occasion_date',o.occasion_date,'occasion_time',o.occasion_time,'delivery_area',o.delivery_area,'delivery_address',o.delivery_address,'customer_note',o.customer_note,'currency',o.currency,'created_at',o.created_at) into v_order from public.orders o where o.id=v_po.order_id;select coalesce(jsonb_agg(jsonb_build_object('id',oi.id,'item_name',oi.item_name,'unit_price',oi.unit_price,'quantity',oi.quantity,'line_total',oi.line_total,'item_snapshot',oi.item_snapshot) order by oi.created_at),'[]'::jsonb) into v_items from public.order_items oi where oi.order_id=v_po.order_id and oi.partner_id=v_po.partner_id;return jsonb_build_object('partner_order',jsonb_build_object('id',v_po.id,'status',v_po.status,'subtotal',v_po.subtotal,'commission_rate',v_po.commission_rate,'commission_amount',v_po.commission_amount,'partner_net',v_po.partner_net,'accepted_at',v_po.accepted_at,'completed_at',v_po.completed_at,'created_at',v_po.created_at),'order',coalesce(v_order,'{}'::jsonb),'items',v_items);end;$$;

create or replace function private.partner_update_order_status_impl(p_partner_order_id uuid,p_status public.partner_order_status)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_uid uuid:=auth.uid();v_po public.partner_orders%rowtype;v_allowed boolean:=false;
begin if v_uid is null then raise exception 'Authentication required' using errcode='42501';end if;select po.* into v_po from public.partner_orders po where po.id=p_partner_order_id for update;if v_po.id is null or not exists(select 1 from public.partner_users pu where pu.partner_id=v_po.partner_id and pu.user_id=v_uid and pu.is_active=true) then raise exception 'Partner order access denied' using errcode='42501';end if;v_allowed:=(v_po.status='pending' and p_status in ('accepted','rejected')) or (v_po.status='accepted' and p_status='in_progress') or (v_po.status='in_progress' and p_status='ready') or (v_po.status='ready' and p_status='completed');if not v_allowed then raise exception 'Invalid partner order status transition: % -> %',v_po.status,p_status;end if;update public.partner_orders set status=p_status,accepted_at=case when p_status='accepted' and accepted_at is null then now() else accepted_at end,completed_at=case when p_status='completed' then now() else completed_at end,updated_at=now() where id=p_partner_order_id;insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(v_uid,'partner_order_status_changed','partner_order',p_partner_order_id::text,jsonb_build_object('status',v_po.status),jsonb_build_object('status',p_status));return jsonb_build_object('partner_order_id',p_partner_order_id,'status',p_status);end;$$;

create or replace function private.partner_list_orders_impl()
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_uid uuid:=auth.uid();v_result jsonb;
begin if v_uid is null then raise exception 'Authentication required' using errcode='42501';end if;if not exists(select 1 from public.profiles p where p.id=v_uid and p.is_active=true and p.role='partner_user') then raise exception 'Partner access required' using errcode='42501';end if;select coalesce(jsonb_agg(row_data order by (row_data->>'created_at')::timestamptz desc),'[]'::jsonb) into v_result from (select jsonb_build_object('partner_order_id',po.id,'partner_id',po.partner_id,'partner_name',coalesce(pa.name_ar,pa.name_en),'status',po.status,'subtotal',po.subtotal,'commission_rate',po.commission_rate,'commission_amount',po.commission_amount,'partner_net',po.partner_net,'accepted_at',po.accepted_at,'completed_at',po.completed_at,'created_at',po.created_at,'order_number',o.order_number,'occasion_type',o.occasion_type,'occasion_date',o.occasion_date,'occasion_time',o.occasion_time,'delivery_area',o.delivery_area,'currency',o.currency,'item_count',(select count(*) from public.order_items oi where oi.order_id=po.order_id and oi.partner_id=po.partner_id)) row_data from public.partner_orders po join public.partner_users pu on pu.partner_id=po.partner_id and pu.user_id=v_uid and pu.is_active=true join public.partners pa on pa.id=po.partner_id join public.orders o on o.id=po.order_id) s;return v_result;end;$$;

revoke all on function private.partner_submit_listing_impl(uuid,uuid,uuid,public.listing_kind,text,text,text,text,numeric,numeric,text,jsonb,boolean,integer,integer,boolean) from public,anon;grant execute on function private.partner_submit_listing_impl(uuid,uuid,uuid,public.listing_kind,text,text,text,text,numeric,numeric,text,jsonb,boolean,integer,integer,boolean) to authenticated;
revoke all on function private.partner_set_inventory_impl(uuid,boolean,integer,integer) from public,anon;grant execute on function private.partner_set_inventory_impl(uuid,boolean,integer,integer) to authenticated;
revoke all on function private.partner_get_order_detail_impl(uuid) from public,anon;grant execute on function private.partner_get_order_detail_impl(uuid) to authenticated;
revoke all on function private.partner_update_order_status_impl(uuid,public.partner_order_status) from public,anon;grant execute on function private.partner_update_order_status_impl(uuid,public.partner_order_status) to authenticated;
revoke all on function private.partner_list_orders_impl() from public,anon;grant execute on function private.partner_list_orders_impl() to authenticated;

create or replace function public.partner_submit_listing(p_listing_id uuid,p_partner_id uuid,p_category_id uuid,p_kind public.listing_kind,p_name_ar text,p_name_en text,p_description_ar text,p_description_en text,p_price numeric,p_compare_at_price numeric,p_currency text,p_media jsonb,p_is_available boolean,p_stock_qty integer,p_capacity_per_day integer,p_submit boolean default true) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$select private.partner_submit_listing_impl(p_listing_id,p_partner_id,p_category_id,p_kind,p_name_ar,p_name_en,p_description_ar,p_description_en,p_price,p_compare_at_price,p_currency,p_media,p_is_available,p_stock_qty,p_capacity_per_day,p_submit);$$;
create or replace function public.partner_set_inventory(p_listing_id uuid,p_is_available boolean,p_stock_qty integer,p_capacity_per_day integer) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$select private.partner_set_inventory_impl(p_listing_id,p_is_available,p_stock_qty,p_capacity_per_day);$$;
create or replace function public.partner_get_order_detail(p_partner_order_id uuid) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$select private.partner_get_order_detail_impl(p_partner_order_id);$$;
create or replace function public.partner_update_order_status(p_partner_order_id uuid,p_status public.partner_order_status) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$select private.partner_update_order_status_impl(p_partner_order_id,p_status);$$;
create or replace function public.partner_list_orders() returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$select private.partner_list_orders_impl();$$;

revoke all on function public.partner_submit_listing(uuid,uuid,uuid,public.listing_kind,text,text,text,text,numeric,numeric,text,jsonb,boolean,integer,integer,boolean) from public,anon;grant execute on function public.partner_submit_listing(uuid,uuid,uuid,public.listing_kind,text,text,text,text,numeric,numeric,text,jsonb,boolean,integer,integer,boolean) to authenticated;
revoke all on function public.partner_set_inventory(uuid,boolean,integer,integer) from public,anon;grant execute on function public.partner_set_inventory(uuid,boolean,integer,integer) to authenticated;
revoke all on function public.partner_get_order_detail(uuid) from public,anon;grant execute on function public.partner_get_order_detail(uuid) to authenticated;
revoke all on function public.partner_update_order_status(uuid,public.partner_order_status) from public,anon;grant execute on function public.partner_update_order_status(uuid,public.partner_order_status) to authenticated;
revoke all on function public.partner_list_orders() from public,anon;grant execute on function public.partner_list_orders() to authenticated;
