-- Dear Day employee RBAC + finance settlement foundation
create table if not exists public.permissions(code text primary key,description text not null);
create table if not exists public.role_permissions(role public.app_role not null,permission_code text not null references public.permissions(code) on delete cascade,primary key(role,permission_code));
create table if not exists public.employee_permission_overrides(user_id uuid not null references public.profiles(id) on delete cascade,permission_code text not null references public.permissions(code) on delete cascade,is_granted boolean not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(user_id,permission_code));

insert into public.permissions(code,description) values
('dashboard.view','View internal dashboard'),('orders.view','View all customer and partner orders'),('orders.manage','Manage customer and partner orders'),('partners.view','View partner records'),('partners.manage','Create and manage partners'),('catalog.view','View full catalog including non-public versions'),('catalog.manage','Create and manage catalog records'),('approvals.review','Approve or reject catalog submissions'),('customers.view','View customer profiles'),('employees.view','View employee accounts and permissions'),('employees.manage','Manage employee roles, access, and permission overrides'),('finance.view','View commissions, partner nets, and settlements'),('finance.manage','Create, approve, and mark settlements paid'),('audit.view','View audit logs'),('audit.write','Write audit events')
on conflict(code) do update set description=excluded.description;

insert into public.role_permissions(role,permission_code) values
('admin','dashboard.view'),('admin','orders.view'),('admin','orders.manage'),('admin','partners.view'),('admin','partners.manage'),('admin','catalog.view'),('admin','catalog.manage'),('admin','approvals.review'),('admin','customers.view'),('admin','employees.view'),('admin','finance.view'),('admin','finance.manage'),('admin','audit.view'),('admin','audit.write'),
('operations','dashboard.view'),('operations','orders.view'),('operations','orders.manage'),('operations','partners.view'),('operations','customers.view'),('operations','audit.write'),
('accountant','dashboard.view'),('accountant','orders.view'),('accountant','partners.view'),('accountant','finance.view'),('accountant','finance.manage'),('accountant','audit.write'),
('partner_manager','dashboard.view'),('partner_manager','orders.view'),('partner_manager','partners.view'),('partner_manager','partners.manage'),('partner_manager','catalog.view'),('partner_manager','approvals.review'),('partner_manager','audit.write'),
('customer_support','dashboard.view'),('customer_support','orders.view'),('customer_support','customers.view'),('marketing','dashboard.view'),('marketing','catalog.view'),
('content_admin','dashboard.view'),('content_admin','catalog.view'),('content_admin','catalog.manage'),('content_admin','audit.write') on conflict do nothing;

create or replace function private.has_permission(p_code text) returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
select exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active=true and (p.role='super_admin'::public.app_role or coalesce((select o.is_granted from public.employee_permission_overrides o where o.user_id=p.id and o.permission_code=p_code),exists(select 1 from public.role_permissions rp where rp.role=p.role and rp.permission_code=p_code))));$$;
revoke all on function private.has_permission(text) from public; grant execute on function private.has_permission(text) to anon,authenticated;

create or replace function private.protect_profile_security_fields() returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin
if tg_op='INSERT' then if (new.role<>'customer'::public.app_role or new.is_active is distinct from true) and not private.has_permission('employees.manage') then raise exception 'You are not allowed to create a privileged account profile'; end if; return new; end if;
if (old.role is distinct from new.role or old.is_active is distinct from new.is_active) and not private.has_permission('employees.manage') then raise exception 'You are not allowed to change account role or active status'; end if; return new; end $$;
drop trigger if exists protect_profile_security_fields on public.profiles; create trigger protect_profile_security_fields before insert or update on public.profiles for each row execute function private.protect_profile_security_fields();

alter table public.permissions enable row level security; alter table public.role_permissions enable row level security; alter table public.employee_permission_overrides enable row level security;
create policy permissions_employee_read on public.permissions for select to authenticated using(private.has_permission('employees.view') or private.has_permission('employees.manage'));
create policy role_permissions_employee_read on public.role_permissions for select to authenticated using(private.has_permission('employees.view') or private.has_permission('employees.manage'));
create policy overrides_employee_read on public.employee_permission_overrides for select to authenticated using(private.has_permission('employees.view') or private.has_permission('employees.manage'));
create policy permissions_employee_manage on public.permissions for all to authenticated using(private.has_permission('employees.manage')) with check(private.has_permission('employees.manage'));
create policy role_permissions_employee_manage on public.role_permissions for all to authenticated using(private.has_permission('employees.manage')) with check(private.has_permission('employees.manage'));
create policy overrides_employee_manage on public.employee_permission_overrides for all to authenticated using(private.has_permission('employees.manage')) with check(private.has_permission('employees.manage'));

-- Scoped RLS replaces the old blanket staff access.
drop policy if exists staff_all_orders on public.orders; drop policy if exists orders_customer_read on public.orders;
create policy orders_read_scoped on public.orders for select to authenticated using(customer_id=(select auth.uid()) or private.has_permission('orders.view'));
create policy orders_manage_scoped on public.orders for update to authenticated using(private.has_permission('orders.manage')) with check(private.has_permission('orders.manage'));

drop policy if exists staff_all_order_items on public.order_items; drop policy if exists order_items_customer_read on public.order_items;
create policy order_items_read_scoped on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_items.order_id and o.customer_id=(select auth.uid())) or private.has_permission('orders.view'));
create policy order_items_manage_scoped on public.order_items for all to authenticated using(private.has_permission('orders.manage')) with check(private.has_permission('orders.manage'));

drop policy if exists staff_all_partner_orders on public.partner_orders; drop policy if exists partner_orders_partner_read on public.partner_orders;
create policy partner_orders_read_scoped on public.partner_orders for select to authenticated using(private.has_permission('orders.view') or private.has_permission('finance.view') or exists(select 1 from public.partner_users pu where pu.partner_id=partner_orders.partner_id and pu.user_id=(select auth.uid()) and pu.is_active=true));
create policy partner_orders_manage_scoped on public.partner_orders for all to authenticated using(private.has_permission('orders.manage')) with check(private.has_permission('orders.manage'));

drop policy if exists staff_all_partners on public.partners; drop policy if exists partners_public_read on public.partners;
create policy partners_public_read on public.partners for select to anon,authenticated using(status='active'::public.partner_status or private.has_permission('partners.view') or private.has_permission('finance.view'));
create policy partners_manage_scoped on public.partners for all to authenticated using(private.has_permission('partners.manage')) with check(private.has_permission('partners.manage'));

drop policy if exists staff_all_categories on public.categories; drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select to anon,authenticated using(is_active=true or private.has_permission('catalog.view'));
create policy categories_manage_scoped on public.categories for all to authenticated using(private.has_permission('catalog.manage')) with check(private.has_permission('catalog.manage'));

drop policy if exists staff_all_listings on public.listings; drop policy if exists listings_public_read on public.listings;
create policy listings_public_read on public.listings for select to anon,authenticated using((is_available=true and published_version_id is not null) or private.has_permission('catalog.view'));
create policy listings_manage_scoped on public.listings for all to authenticated using(private.has_permission('catalog.manage')) with check(private.has_permission('catalog.manage'));

drop policy if exists staff_all_listing_versions on public.listing_versions; drop policy if exists listing_versions_public_read on public.listing_versions;
create policy listing_versions_public_read on public.listing_versions for select to anon,authenticated using(status='published'::public.listing_status or private.has_permission('catalog.view') or private.has_permission('approvals.review'));
create policy listing_versions_manage_scoped on public.listing_versions for all to authenticated using(private.has_permission('catalog.manage')) with check(private.has_permission('catalog.manage'));

drop policy if exists staff_all_audit_logs on public.audit_logs; drop policy if exists staff_insert_audit_logs on public.audit_logs;
create policy audit_view_scoped on public.audit_logs for select to authenticated using(private.has_permission('audit.view'));
create policy audit_insert_scoped on public.audit_logs for insert to authenticated with check(private.has_permission('audit.write') and actor_id=(select auth.uid()));

drop policy if exists profiles_self_read on public.profiles; create policy profiles_self_read on public.profiles for select to authenticated using(id=(select auth.uid()) or private.has_permission('customers.view') or private.has_permission('employees.view') or private.has_permission('employees.manage'));
create policy profiles_employee_manage on public.profiles for update to authenticated using(private.has_permission('employees.manage')) with check(private.has_permission('employees.manage'));
drop policy if exists partner_users_self_read on public.partner_users; create policy partner_users_self_read on public.partner_users for select to authenticated using(user_id=(select auth.uid()) or private.has_permission('partners.view') or private.has_permission('employees.view') or private.has_permission('employees.manage'));

do $$ begin create type public.settlement_status as enum('draft','approved','paid','cancelled'); exception when duplicate_object then null; end $$;
create table if not exists public.partner_settlements(id uuid primary key default gen_random_uuid(),partner_id uuid not null references public.partners(id),period_start date not null,period_end date not null,gross_amount numeric(14,2) not null default 0,commission_amount numeric(14,2) not null default 0,adjustments numeric(14,2) not null default 0,partner_net numeric(14,2) not null default 0,currency text not null default 'EGP',status public.settlement_status not null default 'draft',payment_reference text,notes text,created_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),approved_at timestamptz,paid_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint partner_settlements_period_valid check(period_end>=period_start));
create table if not exists public.settlement_items(settlement_id uuid not null references public.partner_settlements(id) on delete cascade,partner_order_id uuid not null references public.partner_orders(id),gross_amount numeric(14,2) not null,commission_amount numeric(14,2) not null,partner_net numeric(14,2) not null,primary key(settlement_id,partner_order_id),unique(partner_order_id));
create index if not exists partner_settlements_partner_idx on public.partner_settlements(partner_id,created_at desc); create index if not exists partner_settlements_status_idx on public.partner_settlements(status,created_at desc);
alter table public.partner_settlements enable row level security; alter table public.settlement_items enable row level security;
create policy settlements_finance_read on public.partner_settlements for select to authenticated using(private.has_permission('finance.view') or exists(select 1 from public.partner_users pu where pu.partner_id=partner_settlements.partner_id and pu.user_id=(select auth.uid()) and pu.is_active=true and partner_settlements.status in('approved','paid')));
create policy settlements_finance_manage on public.partner_settlements for all to authenticated using(private.has_permission('finance.manage')) with check(private.has_permission('finance.manage'));
create policy settlement_items_finance_read on public.settlement_items for select to authenticated using(private.has_permission('finance.view') or exists(select 1 from public.partner_settlements s join public.partner_users pu on pu.partner_id=s.partner_id where s.id=settlement_items.settlement_id and pu.user_id=(select auth.uid()) and pu.is_active=true and s.status in('approved','paid')));
create policy settlement_items_finance_manage on public.settlement_items for all to authenticated using(private.has_permission('finance.manage')) with check(private.has_permission('finance.manage'));
drop trigger if exists partner_settlements_set_updated_at on public.partner_settlements; create trigger partner_settlements_set_updated_at before update on public.partner_settlements for each row execute function private.set_updated_at();

create or replace function public.get_my_permissions() returns table(permission_code text) language sql stable security invoker set search_path=pg_catalog,public,private as $$ select p.code from public.permissions p where private.has_permission(p.code) order by p.code $$; revoke all on function public.get_my_permissions() from public; grant execute on function public.get_my_permissions() to authenticated;

create or replace function private.employee_directory() returns table(id uuid,email text,full_name text,role public.app_role,is_active boolean,created_at timestamptz) language plpgsql security definer set search_path=pg_catalog,public,auth,private as $$ begin if not(private.has_permission('employees.view') or private.has_permission('employees.manage')) then raise exception 'Permission denied'; end if; return query select p.id,u.email::text,p.full_name,p.role,p.is_active,p.created_at from public.profiles p join auth.users u on u.id=p.id where p.role in('super_admin','admin','operations','accountant','partner_manager','customer_support','marketing','content_admin') order by p.created_at; end $$; revoke all on function private.employee_directory() from public; grant execute on function private.employee_directory() to authenticated;
create or replace function public.employee_list() returns table(id uuid,email text,full_name text,role public.app_role,is_active boolean,created_at timestamptz) language sql security invoker set search_path=pg_catalog,public,private as $$ select * from private.employee_directory() $$; revoke all on function public.employee_list() from public; grant execute on function public.employee_list() to authenticated;

create or replace function public.employee_update_access(p_user_id uuid,p_role public.app_role,p_is_active boolean) returns void language plpgsql security invoker set search_path=pg_catalog,public,private as $$ declare v_old public.profiles%rowtype; v_superadmins integer; begin if not private.has_permission('employees.manage') then raise exception 'Permission denied'; end if; if p_role not in('super_admin','admin','operations','accountant','partner_manager','customer_support','marketing','content_admin') then raise exception 'Invalid employee role'; end if; select * into v_old from public.profiles where id=p_user_id for update; if not found then raise exception 'Employee not found'; end if; if v_old.role in('customer','partner_user') then raise exception 'This account is not an employee account'; end if; if p_user_id=auth.uid() and p_is_active=false then raise exception 'You cannot disable your own account'; end if; if v_old.role='super_admin'::public.app_role and(p_role<>'super_admin'::public.app_role or p_is_active=false) then select count(*) into v_superadmins from public.profiles where role='super_admin'::public.app_role and is_active=true; if v_superadmins<=1 then raise exception 'At least one active Super Admin is required'; end if; end if; update public.profiles set role=p_role,is_active=p_is_active where id=p_user_id; insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),'employee.access_changed','profile',p_user_id::text,jsonb_build_object('role',v_old.role,'is_active',v_old.is_active),jsonb_build_object('role',p_role,'is_active',p_is_active)); end $$; revoke all on function public.employee_update_access(uuid,public.app_role,boolean) from public; grant execute on function public.employee_update_access(uuid,public.app_role,boolean) to authenticated;

create or replace function public.employee_set_permission_override(p_user_id uuid,p_permission_code text,p_is_granted boolean) returns void language plpgsql security invoker set search_path=pg_catalog,public,private as $$ declare v_role public.app_role; begin if not private.has_permission('employees.manage') then raise exception 'Permission denied'; end if; if not exists(select 1 from public.permissions where code=p_permission_code) then raise exception 'Unknown permission'; end if; select role into v_role from public.profiles where id=p_user_id; if v_role is null or v_role in('customer','partner_user') then raise exception 'Overrides are only available for employee accounts'; end if; if p_is_granted is null then delete from public.employee_permission_overrides where user_id=p_user_id and permission_code=p_permission_code; else insert into public.employee_permission_overrides(user_id,permission_code,is_granted) values(p_user_id,p_permission_code,p_is_granted) on conflict(user_id,permission_code) do update set is_granted=excluded.is_granted,updated_at=now(); end if; insert into public.audit_logs(actor_id,action,entity_type,entity_id,after_data) values(auth.uid(),'employee.permission_override_changed','profile',p_user_id::text,jsonb_build_object('permission',p_permission_code,'is_granted',p_is_granted)); end $$; revoke all on function public.employee_set_permission_override(uuid,text,boolean) from public; grant execute on function public.employee_set_permission_override(uuid,text,boolean) to authenticated;

create or replace function public.finance_create_settlement(p_partner_id uuid,p_period_start date,p_period_end date,p_adjustments numeric default 0,p_notes text default null) returns uuid language plpgsql security invoker set search_path=pg_catalog,public,private as $$ declare v_id uuid;v_gross numeric(14,2);v_commission numeric(14,2);v_net numeric(14,2); begin if not private.has_permission('finance.manage') then raise exception 'Permission denied'; end if; if p_period_end<p_period_start then raise exception 'Invalid settlement period'; end if; select coalesce(sum(po.subtotal),0),coalesce(sum(po.commission_amount),0),coalesce(sum(po.partner_net),0) into v_gross,v_commission,v_net from public.partner_orders po where po.partner_id=p_partner_id and po.status='completed'::public.partner_order_status and po.completed_at::date between p_period_start and p_period_end and not exists(select 1 from public.settlement_items si where si.partner_order_id=po.id); if v_gross=0 then raise exception 'No eligible completed partner orders in this period'; end if; insert into public.partner_settlements(partner_id,period_start,period_end,gross_amount,commission_amount,adjustments,partner_net,created_by,notes) values(p_partner_id,p_period_start,p_period_end,v_gross,v_commission,coalesce(p_adjustments,0),v_net+coalesce(p_adjustments,0),auth.uid(),nullif(trim(p_notes),'')) returning id into v_id; insert into public.settlement_items(settlement_id,partner_order_id,gross_amount,commission_amount,partner_net) select v_id,po.id,po.subtotal,po.commission_amount,po.partner_net from public.partner_orders po where po.partner_id=p_partner_id and po.status='completed'::public.partner_order_status and po.completed_at::date between p_period_start and p_period_end and not exists(select 1 from public.settlement_items si where si.partner_order_id=po.id); insert into public.audit_logs(actor_id,action,entity_type,entity_id,after_data) values(auth.uid(),'settlement.created','partner_settlement',v_id::text,jsonb_build_object('partner_id',p_partner_id,'period_start',p_period_start,'period_end',p_period_end,'partner_net',v_net+coalesce(p_adjustments,0))); return v_id; end $$; revoke all on function public.finance_create_settlement(uuid,date,date,numeric,text) from public; grant execute on function public.finance_create_settlement(uuid,date,date,numeric,text) to authenticated;

create or replace function public.finance_update_settlement_status(p_settlement_id uuid,p_status public.settlement_status,p_payment_reference text default null) returns public.settlement_status language plpgsql security invoker set search_path=pg_catalog,public,private as $$ declare v_current public.settlement_status; begin if not private.has_permission('finance.manage') then raise exception 'Permission denied'; end if; select status into v_current from public.partner_settlements where id=p_settlement_id for update; if v_current is null then raise exception 'Settlement not found'; end if; if not((v_current='draft' and p_status in('approved','cancelled')) or(v_current='approved' and p_status in('paid','cancelled')) or v_current=p_status) then raise exception 'Invalid settlement status transition'; end if; if p_status='paid' and nullif(trim(p_payment_reference),'') is null then raise exception 'Payment reference is required'; end if; update public.partner_settlements set status=p_status,approved_by=case when p_status='approved' then auth.uid() else approved_by end,approved_at=case when p_status='approved' then now() else approved_at end,paid_at=case when p_status='paid' then now() else paid_at end,payment_reference=case when p_status='paid' then trim(p_payment_reference) else payment_reference end where id=p_settlement_id; insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),'settlement.status_changed','partner_settlement',p_settlement_id::text,jsonb_build_object('status',v_current),jsonb_build_object('status',p_status,'payment_reference',p_payment_reference)); return p_status; end $$; revoke all on function public.finance_update_settlement_status(uuid,public.settlement_status,text) from public; grant execute on function public.finance_update_settlement_status(uuid,public.settlement_status,text) to authenticated;
