insert into public.categories(slug,name_ar,name_en,sort_order,is_active) values
('gifts','هدايا','Gifts',10,true),
('cakes-sweets','كيك وحلويات','Cakes & Sweets',20,true),
('flowers','ورد','Flowers',30,true),
('places-experiences','أماكن وتجارب','Places & Experiences',40,true)
on conflict(slug) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,sort_order=excluded.sort_order,is_active=true;

do $$
declare
  v_partner uuid;
  v_item jsonb;
  v_category uuid;
  v_listing uuid;
  v_version uuid;
  v_existing uuid;
  v_stock int;
  v_capacity int;
begin
  select id into v_partner from public.partners where slug='test-partner-giza' and status='active' limit 1;
  if v_partner is null then raise exception 'Active demo partner not found'; end if;

  for v_item in
    select value from jsonb_array_elements($demo$
[
{"demo_key":"gift-perfume-signature","section":"gifts","name_ar":"عطر سيجنتشر","name_en":"Signature Perfume","description_ar":"عطر أنيق بتغليف هدية بسيط، مناسب للميلاد والذكرى والمناسبات الخاصة.","price":1850,"image":"/approved-pages/assets/media/gift-perfume.svg","subcategory":"perfumes","recipient":["her","him"],"occasions":["birthday","anniversary","engagement"],"brand":"Demo Atelier","same_day":true,"personalized":false,"tags":["best_seller"],"prep_hours":4},
{"demo_key":"gift-watch-minimal","section":"gifts","name_ar":"ساعة مينيمال","name_en":"Minimal Watch","description_ar":"ساعة بتصميم بسيط وعلبة هدية جاهزة للتقديم.","price":2400,"image":"/approved-pages/assets/media/gift-watch.svg","subcategory":"watches","recipient":["him","her"],"occasions":["birthday","anniversary","graduation"],"brand":"Demo House","same_day":true,"personalized":false,"tags":["new"],"prep_hours":4},
{"demo_key":"gift-bracelet-initial","section":"gifts","name_ar":"سوار بحرف","name_en":"Initial Bracelet","description_ar":"سوار بسيط يمكن تخصيصه بحرف واحد كلمسة شخصية.","price":1250,"image":"/approved-pages/assets/media/gift-bracelet.svg","subcategory":"jewelry","recipient":["her"],"occasions":["birthday","anniversary","engagement"],"brand":"Demo Atelier","same_day":false,"personalized":true,"tags":["best_seller"],"prep_hours":24},
{"demo_key":"gift-necklace-elegant","section":"gifts","name_ar":"سلسلة رقيقة","name_en":"Delicate Necklace","description_ar":"سلسلة أنيقة خفيفة بتغليف هدية هادئ.","price":1450,"image":"/approved-pages/assets/media/gift-necklace.svg","subcategory":"jewelry","recipient":["her"],"occasions":["birthday","anniversary","engagement"],"brand":"Demo Atelier","same_day":true,"personalized":false,"tags":[],"prep_hours":6},
{"demo_key":"gift-ring-minimal","section":"gifts","name_ar":"خاتم مينيمال","name_en":"Minimal Ring","description_ar":"خاتم بسيط بتصميم يومي أنيق.","price":1350,"image":"/approved-pages/assets/media/gift-ring.svg","subcategory":"jewelry","recipient":["her"],"occasions":["birthday","anniversary","engagement"],"brand":"Demo Atelier","same_day":true,"personalized":false,"tags":["new"],"prep_hours":6},
{"demo_key":"gift-personalized-keepsake","section":"gifts","name_ar":"هدية باسم مخصص","name_en":"Personalized Keepsake","description_ar":"قطعة تذكارية مخصصة بالاسم أو رسالة قصيرة.","price":950,"image":"/approved-pages/assets/media/personalized-gift.svg","subcategory":"personalized","recipient":["her","him","friend"],"occasions":["birthday","anniversary","graduation"],"brand":"Demo Studio","same_day":false,"personalized":true,"tags":["best_seller"],"prep_hours":24},
{"demo_key":"gift-selfcare-box","section":"gifts","name_ar":"بوكس عناية وراحة","name_en":"Self-care Box","description_ar":"بوكس هادئ يجمع منتجات عناية واسترخاء في تغليف جاهز.","price":1650,"image":"/approved-pages/assets/media/custom-gift-box.jpg","subcategory":"gift_sets","recipient":["her","friend"],"occasions":["birthday","thank_you","get_well"],"brand":"Demo Studio","same_day":true,"personalized":false,"tags":[],"prep_hours":6},
{"demo_key":"gift-coffee-box","section":"gifts","name_ar":"بوكس قهوة ومج","name_en":"Coffee & Mug Box","description_ar":"بوكس قهوة ومج بتنسيق بسيط مناسب لهدية يومية.","price":1100,"image":"/approved-pages/assets/media/custom-gift-box.jpg","subcategory":"gift_sets","recipient":["him","friend"],"occasions":["birthday","thank_you","graduation"],"brand":"Demo House","same_day":true,"personalized":false,"tags":[],"prep_hours":6},
{"demo_key":"gift-home-scent","section":"gifts","name_ar":"مجموعة عطر منزلي","name_en":"Home Scent Set","description_ar":"مجموعة عطر منزلي بتغليف أنيق للمنازل الجديدة والمناسبات.","price":1550,"image":"/approved-pages/assets/media/occasion-gift.jpg","subcategory":"home_decor","recipient":["her","him","couple"],"occasions":["housewarming","anniversary","engagement"],"brand":"Demo House","same_day":true,"personalized":false,"tags":["new"],"prep_hours":6},
{"demo_key":"gift-leather-set","section":"gifts","name_ar":"طقم جلد عملي","name_en":"Leather Essentials Set","description_ar":"طقم عملي صغير من الإكسسوارات الجلدية بتغليف هدية.","price":1950,"image":"/approved-pages/assets/media/occasion-gift.jpg","subcategory":"accessories","recipient":["him"],"occasions":["birthday","graduation","anniversary"],"brand":"Demo House","same_day":true,"personalized":false,"tags":[],"prep_hours":6},
{"demo_key":"gift-chocolate-box","section":"gifts","name_ar":"بوكس شوكولاتة هدية","name_en":"Chocolate Gift Box","description_ar":"بوكس شوكولاتة منسق وجاهز للتقديم.","price":980,"image":"/approved-pages/assets/media/dessert-box.jpg","subcategory":"chocolate_gifts","recipient":["her","him","friend"],"occasions":["birthday","anniversary","thank_you"],"brand":"Demo Cocoa","same_day":true,"personalized":false,"tags":["best_seller"],"prep_hours":4},
{"demo_key":"gift-memory-box","section":"gifts","name_ar":"بوكس ذكريات","name_en":"Memory Box","description_ar":"بوكس قابل للتخصيص برسالة وصور مختارة من العميل.","price":1400,"image":"/approved-pages/assets/media/custom-gift-box.jpg","subcategory":"personalized","recipient":["her","him","friend"],"occasions":["birthday","anniversary","graduation"],"brand":"Demo Studio","same_day":false,"personalized":true,"tags":[],"prep_hours":24},
{"demo_key":"gift-desk-set","section":"gifts","name_ar":"هدية مكتب أنيقة","name_en":"Desk Gift Set","description_ar":"طقم مكتب بسيط مناسب للترقية والتخرج والشكر.","price":1750,"image":"/approved-pages/assets/media/occasion-gift.jpg","subcategory":"accessories","recipient":["him","her"],"occasions":["graduation","promotion","thank_you"],"brand":"Demo House","same_day":true,"personalized":false,"tags":["new"],"prep_hours":6},
{"demo_key":"gift-plant-pot","section":"gifts","name_ar":"نبات صغير بوعاء","name_en":"Mini Plant Pot","description_ar":"نبات صغير سهل العناية في وعاء بسيط كهدية خفيفة.","price":850,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","subcategory":"plants","recipient":["her","him","friend"],"occasions":["housewarming","thank_you","birthday"],"brand":"Demo Green","same_day":true,"personalized":false,"tags":[],"prep_hours":4},
{"demo_key":"gift-couple-box","section":"gifts","name_ar":"بوكس للثنائي","name_en":"Couple Gift Box","description_ar":"بوكس ثنائي قابل لإضافة أسماء أو رسالة قصيرة.","price":2200,"image":"/approved-pages/assets/media/custom-gift-box.jpg","subcategory":"gift_sets","recipient":["couple"],"occasions":["anniversary","engagement","wedding"],"brand":"Demo Studio","same_day":false,"personalized":true,"tags":["best_seller"],"prep_hours":24},

{"demo_key":"cake-chocolate-classic","section":"cakes-sweets","name_ar":"تورتة شوكولاتة كلاسيك","name_en":"Classic Chocolate Cake","description_ar":"تورتة شوكولاتة كلاسيكية بطبقات غنية تكفي تجمعًا صغيرًا.","price":1250,"image":"/approved-pages/assets/media/cake-chocolate-premium.jpg","subcategory":"cakes","occasions":["birthday","anniversary"],"brand":"Demo Bake","prep_hours":12,"serves":"8-10","flavor":"chocolate","tags":["best_seller"]},
{"demo_key":"cake-vanilla-berry","section":"cakes-sweets","name_ar":"تورتة فانيليا وتوت","name_en":"Vanilla Berry Cake","description_ar":"تورتة فانيليا خفيفة بلمسة توت وتزيين بسيط.","price":1450,"image":"/approved-pages/assets/media/cake-vanilla-classic.jpg","subcategory":"cakes","occasions":["birthday","anniversary","engagement"],"brand":"Demo Bake","prep_hours":12,"serves":"8-10","flavor":"vanilla","tags":["new"]},
{"demo_key":"cake-lotus","section":"cakes-sweets","name_ar":"تورتة لوتس","name_en":"Lotus Cake","description_ar":"تورتة لوتس بتزيين هادئ ونكهة بسكويت واضحة.","price":1550,"image":"/approved-pages/assets/media/cake-lotus-minimal.jpg","subcategory":"cakes","occasions":["birthday","anniversary"],"brand":"Demo Bake","prep_hours":12,"serves":"8-10","flavor":"lotus","tags":["best_seller"]},
{"demo_key":"cake-custom-message","section":"cakes-sweets","name_ar":"تورتة برسالة مخصصة","name_en":"Custom Message Cake","description_ar":"تورتة قابلة لإضافة رسالة قصيرة واختيار شكل بسيط.","price":1800,"image":"/approved-pages/assets/media/custom-cake.jpg","subcategory":"custom_cakes","occasions":["birthday","graduation","proposal"],"brand":"Demo Bake","prep_hours":24,"serves":"10-12","flavor":"vanilla","tags":[]},
{"demo_key":"cake-birthday-tall","section":"cakes-sweets","name_ar":"تورتة عيد ميلاد طويلة","name_en":"Tall Birthday Cake","description_ar":"تورتة أطول لمظهر احتفالي مناسب لعيد الميلاد.","price":2300,"image":"/approved-pages/assets/media/birthday-cake.jpg","subcategory":"cakes","occasions":["birthday"],"brand":"Demo Patisserie","prep_hours":24,"serves":"12-16","flavor":"chocolate","tags":["new"]},
{"demo_key":"cake-cupcakes-box","section":"cakes-sweets","name_ar":"بوكس كب كيك","name_en":"Cupcake Box","description_ar":"بوكس كب كيك متنوع مناسب للتجمعات الصغيرة.","price":950,"image":"/approved-pages/assets/media/cupcakes-mixed.jpg","subcategory":"cupcakes","occasions":["birthday","thank_you","baby_shower"],"brand":"Demo Patisserie","prep_hours":8,"serves":"6-8","flavor":"mixed","tags":[]},
{"demo_key":"cake-cookies-box","section":"cakes-sweets","name_ar":"بوكس كوكيز","name_en":"Cookies Box","description_ar":"بوكس كوكيز طازج بنكهات متنوعة.","price":780,"image":"/approved-pages/assets/media/cookies.jpg","subcategory":"desserts","occasions":["birthday","thank_you","graduation"],"brand":"Demo Bake","prep_hours":6,"serves":"6-8","flavor":"mixed","tags":[]},
{"demo_key":"cake-dessert-box","section":"cakes-sweets","name_ar":"بوكس حلويات مشكلة","name_en":"Mixed Dessert Box","description_ar":"بوكس حلويات صغيرة متنوعة للتقديم أو الإهداء.","price":1150,"image":"/approved-pages/assets/media/dessert-box.jpg","subcategory":"dessert_boxes","occasions":["birthday","anniversary","thank_you"],"brand":"Demo Patisserie","prep_hours":8,"serves":"6-8","flavor":"mixed","tags":["best_seller"]},
{"demo_key":"cake-chocolate-mini","section":"cakes-sweets","name_ar":"ميني تورتة شوكولاتة","name_en":"Mini Chocolate Cake","description_ar":"تورتة صغيرة لشخصين إلى أربعة، مناسبة لمفاجأة بسيطة.","price":890,"image":"/approved-pages/assets/media/chocolate-cake.jpg","subcategory":"mini_cakes","occasions":["birthday","anniversary"],"brand":"Demo Bake","prep_hours":8,"serves":"2-4","flavor":"chocolate","tags":[]},
{"demo_key":"cake-engagement-white","section":"cakes-sweets","name_ar":"تورتة خطوبة بسيطة","name_en":"Minimal Engagement Cake","description_ar":"تورتة خطوبة بتصميم أبيض بسيط وقابل للتخصيص.","price":2600,"image":"/approved-pages/assets/media/custom-cake.jpg","subcategory":"custom_cakes","occasions":["engagement"],"brand":"Demo Patisserie","prep_hours":36,"serves":"16-20","flavor":"vanilla","tags":[]},
{"demo_key":"cake-brownie-box","section":"cakes-sweets","name_ar":"بوكس براونيز","name_en":"Brownie Box","description_ar":"بوكس براونيز شوكولاتة مقطع وجاهز للتقديم.","price":820,"image":"/approved-pages/assets/media/dessert-box.jpg","subcategory":"desserts","occasions":["birthday","thank_you","graduation"],"brand":"Demo Cocoa","prep_hours":6,"serves":"6-8","flavor":"chocolate","tags":["new"]},
{"demo_key":"cake-celebration-large","section":"cakes-sweets","name_ar":"تورتة احتفال كبيرة","name_en":"Large Celebration Cake","description_ar":"تورتة كبيرة قابلة للتنسيق حسب ألوان المناسبة.","price":3200,"image":"/approved-pages/assets/media/cake-hero.jpg","subcategory":"custom_cakes","occasions":["birthday","engagement","anniversary"],"brand":"Demo Patisserie","prep_hours":48,"serves":"20-25","flavor":"mixed","tags":[]},

{"demo_key":"flower-red-roses-12","section":"flowers","name_ar":"بوكيه 12 وردة حمراء","name_en":"12 Red Roses Bouquet","description_ar":"بوكيه ورد أحمر كلاسيكي للمناسبات الرومانسية.","price":1150,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"roses","color":"red","stems":12,"occasions":["anniversary","proposal","birthday"],"brand":"Demo Petal","same_day":true,"prep_hours":4,"tags":["best_seller"]},
{"demo_key":"flower-pink-mix","section":"flowers","name_ar":"بوكيه ورد وردي مشكل","name_en":"Pink Mixed Bouquet","description_ar":"تنسيق ورد وردي خفيف للميلاد والشكر والذكرى.","price":1350,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"mixed","color":"pink","stems":18,"occasions":["birthday","thank_you","anniversary"],"brand":"Demo Petal","same_day":true,"prep_hours":4,"tags":[]},
{"demo_key":"flower-white-elegance","section":"flowers","name_ar":"بوكيه أبيض هادئ","name_en":"White Elegance Bouquet","description_ar":"بوكيه بدرجات بيضاء هادئة للخطوبة والذكرى والشكر.","price":1500,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"mixed","color":"white","stems":20,"occasions":["engagement","anniversary","thank_you"],"brand":"Demo Petal","same_day":true,"prep_hours":6,"tags":["new"]},
{"demo_key":"flower-red-box","section":"flowers","name_ar":"بوكس ورد أحمر","name_en":"Red Rose Box","description_ar":"بوكس ورد أحمر بتنسيق مرتب للمناسبات الرومانسية.","price":1850,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"box","flower_type":"roses","color":"red","stems":20,"occasions":["anniversary","proposal"],"brand":"Demo Roseraie","same_day":true,"prep_hours":6,"tags":["best_seller"]},
{"demo_key":"flower-pink-box","section":"flowers","name_ar":"بوكس ورد وردي","name_en":"Pink Flower Box","description_ar":"بوكس ورد وردي للميلاد والخطوبة والشكر.","price":1750,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"box","flower_type":"mixed","color":"pink","stems":20,"occasions":["birthday","engagement","thank_you"],"brand":"Demo Roseraie","same_day":true,"prep_hours":6,"tags":[]},
{"demo_key":"flower-vase-white","section":"flowers","name_ar":"فازة ورد أبيض","name_en":"White Flower Vase","description_ar":"تنسيق ورد أبيض داخل فازة بسيطة للمنازل والمناسبات.","price":2100,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"vase","flower_type":"mixed","color":"white","stems":24,"occasions":["housewarming","anniversary","engagement"],"brand":"Demo Roseraie","same_day":false,"prep_hours":12,"tags":[]},
{"demo_key":"flower-vase-colorful","section":"flowers","name_ar":"فازة ورد ملون","name_en":"Colorful Flower Vase","description_ar":"فازة ورد بألوان متنوعة للميلاد والتخرج والشكر.","price":1950,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"vase","flower_type":"mixed","color":"mixed","stems":24,"occasions":["birthday","thank_you","graduation"],"brand":"Demo Petal","same_day":false,"prep_hours":12,"tags":["new"]},
{"demo_key":"flower-sunflower","section":"flowers","name_ar":"بوكيه دوار شمس","name_en":"Sunflower Bouquet","description_ar":"بوكيه دوار شمس مشرق للميلاد والتخرج والشكر.","price":1200,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"sunflower","color":"yellow","stems":10,"occasions":["birthday","graduation","thank_you"],"brand":"Demo Petal","same_day":true,"prep_hours":4,"tags":[]},
{"demo_key":"flower-baby-breath","section":"flowers","name_ar":"بوكيه جيبسوفيلا","name_en":"Baby's Breath Bouquet","description_ar":"بوكيه جيبسوفيلا أبيض خفيف وبسيط.","price":980,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"gypsophila","color":"white","stems":16,"occasions":["birthday","engagement","thank_you"],"brand":"Demo Petal","same_day":true,"prep_hours":4,"tags":[]},
{"demo_key":"flower-roses-24","section":"flowers","name_ar":"بوكيه 24 وردة","name_en":"24 Roses Bouquet","description_ar":"بوكيه أكبر من الورد الأحمر للذكرى وطلب الزواج.","price":2100,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"roses","color":"red","stems":24,"occasions":["anniversary","proposal"],"brand":"Demo Roseraie","same_day":false,"prep_hours":8,"tags":[]},
{"demo_key":"flower-pastel","section":"flowers","name_ar":"بوكيه باستيل","name_en":"Pastel Bouquet","description_ar":"بوكيه بدرجات باستيل هادئة للميلاد والخطوبة.","price":1650,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"mixed","color":"pastel","stems":20,"occasions":["birthday","engagement","baby_shower"],"brand":"Demo Petal","same_day":true,"prep_hours":6,"tags":["best_seller"]},
{"demo_key":"flower-purple","section":"flowers","name_ar":"بوكيه موف","name_en":"Purple Bouquet","description_ar":"بوكيه بدرجات موف للميلاد والتخرج والشكر.","price":1450,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bouquet","flower_type":"mixed","color":"purple","stems":18,"occasions":["birthday","graduation","thank_you"],"brand":"Demo Petal","same_day":true,"prep_hours":6,"tags":[]},
{"demo_key":"flower-mini-box","section":"flowers","name_ar":"بوكس ورد ميني","name_en":"Mini Flower Box","description_ar":"بوكس ورد صغير لهدية خفيفة ومناسبة للشكر.","price":990,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"box","flower_type":"mixed","color":"pink","stems":10,"occasions":["birthday","thank_you"],"brand":"Demo Roseraie","same_day":true,"prep_hours":4,"tags":[]},
{"demo_key":"flower-luxury-box","section":"flowers","name_ar":"بوكس ورد فاخر","name_en":"Luxury Flower Box","description_ar":"بوكس ورد أكبر للمناسبات الخاصة والخطوبة.","price":3200,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"box","flower_type":"roses","color":"mixed","stems":36,"occasions":["anniversary","proposal","engagement"],"brand":"Demo Roseraie","same_day":false,"prep_hours":12,"tags":["new"]},
{"demo_key":"flower-bridal-hand","section":"flowers","name_ar":"بوكيه عروسة أبيض","name_en":"White Bridal Bouquet","description_ar":"بوكيه يدوي أبيض للعروسة والخطوبة بتنسيق بسيط.","price":2800,"image":"/approved-pages/assets/media/flowers-bouquet.jpg","arrangement":"bridal","flower_type":"mixed","color":"white","stems":30,"occasions":["wedding","engagement"],"brand":"Demo Roseraie","same_day":false,"prep_hours":24,"tags":[]}
]
$demo$::jsonb)
  loop
    select lv.listing_id into v_existing
    from public.listing_versions lv
    where lv.metadata->>'demo_key'=v_item->>'demo_key'
    order by lv.created_at desc limit 1;

    if v_existing is null then
      select id into v_category from public.categories where slug=v_item->>'section';
      v_stock:=case when v_item->>'section'='cakes-sweets' then 20 when v_item->>'section'='flowers' then 25 else 30 end;
      v_capacity:=case when v_item->>'section'='cakes-sweets' then 20 else 40 end;

      insert into public.listings(partner_id,category_id,kind,is_available,stock_qty,capacity_per_day)
      values(v_partner,v_category,'product'::public.listing_kind,true,v_stock,v_capacity)
      returning id into v_listing;

      insert into public.listing_versions(listing_id,status,name_ar,name_en,description_ar,price,currency,media,metadata,submitted_at,reviewed_at)
      values(
        v_listing,'published'::public.listing_status,v_item->>'name_ar',v_item->>'name_en',v_item->>'description_ar',
        (v_item->>'price')::numeric,'EGP',
        jsonb_build_array(jsonb_build_object('url',v_item->>'image','alt_ar',v_item->>'name_ar','alt_en',v_item->>'name_en')),
        (v_item - 'section' - 'name_ar' - 'name_en' - 'description_ar' - 'price' - 'image') || jsonb_build_object('is_demo',true,'catalog_section',v_item->>'section'),
        now(),now()
      ) returning id into v_version;

      update public.listings set published_version_id=v_version where id=v_listing;

      insert into public.listing_availability_settings(listing_id,booking_enabled,booking_mode,timezone,daily_capacity,cutoff_hours,hold_minutes)
      values(v_listing,true,'date'::public.booking_mode,'Africa/Cairo',v_capacity,coalesce((v_item->>'prep_hours')::int,4),15)
      on conflict(listing_id) do update set booking_enabled=true,booking_mode='date'::public.booking_mode,daily_capacity=excluded.daily_capacity,cutoff_hours=excluded.cutoff_hours,updated_at=now();
    end if;
  end loop;
end $$;
